// Copyright (C) Jessie Grosen 2024
// SPDX-License-Identifier: MIT

export global ScaleControls {
    callback zero();
}

export struct ScaleStatus {
    valid: bool,
    weight: float,
}

export global ScaleStatusUtils {
    public pure function to-text(status: ScaleStatus) -> string {
        if (status.valid) {
            "\{round(status.weight * 1000.0)}g"
        } else {
            "------"
        }
    }
}